### ISSUE TITLE
Unable to open gerbers exported from EasyEDA

### ISSUE THREAD

**Issue by scaytrase** [OpenBuilds/cam#43]
I'm trying to open my easyeda project to the cam. selecting gerbers gives me

```
main.js:92 New FileOpen Event:
main.js:93 Event
main.js:78 TypeError: Cannot read property 'length' of undefined

(https://cam.openbuilds.com/lib/gerber/gerberparser.js line 8)
gerberparser.js:8 Uncaught TypeError: Cannot read property 'length' of undefined
    at parseGerber (gerberparser.js:8)
    at FileReader.r.onload (main.js:243)
```

also excellon files could not be selected, since no *.DRL format is supported

Gerber archive attached

[Gerber_separate-spindle-board_20190228201511.zip](https://github.com/OpenBuilds/cam/files/2932791/Gerber_separate-spindle-board_20190228201511.zip)

**Comment by openbuilds-engineer** [comment]
Only tested with Eagle. 

Checkout https://www.youtube.com/watch?v=0pjSeT0OACI 

Will check your files at some point though, leaving open for now

**Comment by openbuilds-engineer** [comment]
Post some screenshots and easyeda files too

**Comment by scaytrase** [comment]
it's pretty simple so I expected it to work, but...

[separate-spindle-board.zip](https://github.com/OpenBuilds/cam/files/2933569/separate-spindle-board.zip)



![image](https://user-images.githubusercontent.com/6578413/53844410-a36df180-3fb6-11e9-9727-b36d8207d315.png)

**Comment by openbuilds-engineer** [comment]
Unfortunately at this time I'll close this issue:

1. EasyEDA being a product for LCSC might not spit out correct Gerber X274 format files, it may be custom to their internal workflow so you can order boards from them
2. EasyEDA user base is very limited.  Eagle is huge, Kicad too. 
3. The file fails to parse in https://github.com/OpenBuilds/cam/tree/master/lib/gerber - I simply cannot afford the time to debug why due to the limited user count. Sorry (:

**Comment by scaytrase** [comment]
Well, currently I use EasyEDA with FlatCAM + Candle without any issue, it's used not only for ordering boards from JLCPCB

**Comment by openbuilds-engineer** [comment]
Cool, glad you got a solution.  As mentioned though, that was a "may be" ^ 
The rest still stands. 

Thanks
